# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
email_provider_username: <%= ENV["soleteamNY@gmail.com"] %>
email_provider_password: <%= ENV["Rockstar1!"] %>
mailchimp_api_key: <%= ENV["e4642d9951712fc559d30f82a3f677f5-us9"] %>
mailchimp_list_id: <%= ENV["82805ab09f"] %>
domain_name: sole-team.com
owner_email: <%= ENV["soleteamNY@gmail.com"] %>
secret_key_base: 20b6bcd564a1d26e05ed6e10da1e999a257bed130e8027a9b1199deb27b9101cce73b364cd7984079012592a287c337453c12c47218138e1fae7514dd21365db
test:
secret_key_base: 20b6bcd564a1d26e05ed6e10da1e999a257bed130e8027a9b1199deb27b9101cce73b364cd7984079012592a287c337453c12c47218138e1fae7514dd21365db
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
email_provider_username: <%= ENV["soleteamNY@gmail.com"] %>
email_provider_password: <%= ENV["Rockstar1!"] %>
mailchimp_api_key: <%= ENV["e4642d9951712fc559d30f82a3f677f5-us9"] %>
mailchimp_list_id: <%= ENV["82805ab09f"] %>
domain_name: <%= ENV["sole-team.com"] %>
owner_email: <%= ENV["soleteamNY@gmail.com"] %>
secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
